#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Left3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Right3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Angler,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define JOY_THROTTLE Ch4
#define JOY_TURN Ch3
task DriveMotors()
{
	while(true)
	{
		if(abs(vexRT[JOY_THROTTLE])<20 && abs(vexRT[JOY_TURN])<20)
		{
			motor[Left1]=motor[Left2]=motor[Left3] = 0;
			motor[Right1]=motor[Right2]=motor[Right3] = 0;
		}
		else
		{
			motor[Left1]=motor[Left2]=motor[Left3] = vexRT[JOY_THROTTLE]-vexRT[JOY_TURN];
			motor[Right1]=motor[Right2]=motor[Right3]=vexRT[JOY_THROTTLE]+vexRT[JOY_TURN];
		}
	}
}

task IntakeAngle()
{
	int StickVal;
	while(true)
	{
		StickVal = abs(vexRT[Ch1]);
		if(abs(vexRT[Ch1])<15)
		{
			motor[Angler] = 10;
		}
		else
		{
			motor[Angler] = vexRT[Ch1];
		}
	}
}
task main()
{

	bool shiftIntake = false;
	bool shiftIntakeBack = false;
	while(true)
	{
		startTask(DriveMotors);
		startTask(IntakeAngle);
		if(vexRT(Btn6U))
		{
			if(!shiftIntake)
			{
				motor[Intake] = -127;
				shiftIntake = true;
			}
			else {shiftIntake= false;  motor[Intake] = 0;}
		}
		if(vexRT(Btn6D))
		{
			if(!shiftIntakeBack)
			{
				motor[Intake] = 127;
				shiftIntakeBack = true;
			}
			else {shiftIntakeBack= false;  motor[Intake] = 0;}
		}
	}

}
