#pragma config(Motor,  port2,           Left1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           Left2,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           Left3,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Right1,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Right2,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           Right3,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Angler,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Intake,        tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#define JOY_THROTTLE vexRT[Ch3]
#define JOY_TURN vexRT[Ch4]
task DriveMotors()
{
	while(true)
	{
		motor[Left1]=motor[Left2]=motor[Left3] = vexRT(JOY_THROTTLE)+vexRT(JOY_TURN);
		motor[Right1]=motor[Right2]=motor[Right3]=vexRT(JOY_THROTTLE)-vexRT(JOY_TURN);
	}
}
task IntakeAngle()
{
	while(true)
	{
		if(vexRT[Ch1]<10)
		{
			motor[Intake] = -10;
		}
		else
		{
			motor[Intake] = vexRT[Ch1];
		}
	}
}
task main()
{
	startTask(DriveMotors);
	startTask(IntakeAngle);
	bool shiftIntake = false;
	while(true)
	{
		if(vexRT(Btn6U))
		{
			if(!shiftIntake)
			{
				motor[Intake] = 127;
				shiftIntake = true;
			}
			else {shiftIntake= false; motor[Intake]=0;}
		}
	}

}
