#pragma config(Sensor, in1,    autoPoti,       sensorPotentiometer)
#pragma config(Sensor, in2,    mobilePoti,     sensorPotentiometer)
#pragma config(Sensor, in3,    liftPoti,       sensorPotentiometer)
#pragma config(Sensor, in4,    armPoti,        sensorPotentiometer)
#pragma config(Sensor, in5,    limLift,         sensorAnalog)
#pragma config(Sensor, in6,    lsBarL,         sensorReflection)
#pragma config(Sensor, in7,    lsBarR,         sensorReflection)
#pragma config(Sensor, in8,    lsMobile,       sensorReflection)
#pragma config(Sensor, dgtl1,  trackL,         sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  trackR,         sensorQuadEncoder)
#pragma config(Sensor, dgtl5,  trackB,         sensorQuadEncoder)
#pragma config(Sensor, dgtl7,  sonarL,         sensorSONAR_mm)
#pragma config(Sensor, dgtl9,  limArm,         sensorTouch)
#pragma config(Sensor, dgtl10, jmpSkills,      sensorDigitalIn)
#pragma config(Sensor, dgtl11, sonarR,         sensorSONAR_mm)
#pragma config(Motor,  port2,           liftR,         tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           driveL1,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           driveL2,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           arm,           tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           mobile,        tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port7,           driveR2,       tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           driveR1,       tmotorVex393TurboSpeed_MC29, openLoop)
#pragma config(Motor,  port9,           liftL,         tmotorVex393HighSpeed_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//
#include "defines.h"
#include "armliftfunctions.h"
#include "drive.h"

bool ManualDrive = true;

task MoveBack()
{
	bool LeftTurn = false;
	bool RightTurn = false;
	bool ManualDrive = false;
	// set motor speeds
	setLeft(-60);
	setRight(-60);
	resetTracking();
	while(abs(SensorValue[trackL])<180)
	{
		if(!ManualDrive)
		{
			if(vexRT(Btn5U))
			{
				LeftTurn = true;
			}
			if(vexRT(Btn6U))
			{
				RightTurn = true;
			}
		}
		if(LeftTurn)
		{
			resetTracking();
			while(abs(trackingL)<90)
			{
				while(trackingL<18)
				{
					setLeft(127);
					setRight(-127);
				}
				while(trackingL<85)
				{
					setLeft(40);
					setRight(-40);
				}
				setLeft(-15);
				setRight(15);
			}
			KillDrive();
		}
		float Timeout = nPgmTime;
		while(Timeout+1000<nPgmTime)
		{
			if(RightTurn)
			{
				resetTracking();
				while(abs(trackingR)<90)
				{
					while(trackingR<18)
					{
						setLeft(-127);
						setRight(127);
					}
					while(trackingR<85)
					{
						setLeft(-40);
						setRight(40);
					}
					setLeft(15);
					setRight(-15);
				}
				KillDrive();
			}
		}
	}
	KillDrive();
	ManualDrive = true;
}

task DriveMotors()
{
	setLeft(vexRT(JOY_THROTTLE)+vexRT(JOY_TURN));
	setRight(vexRT(JOY_THROTTLE)-vexRT(JOY_TURN));
}
task main()
{

	while(true)
	{
		if(ManualDrive){ startTask(DriveMotors);}
		else{stopTask(DriveMotors);}
		bool shiftStack = false;
		if(vexRT(Btn8L))
		{
			if(!shiftStack)
			{
				ManualDrive = false;
				stopTask(MoveBack);
				startTask(MoveBack);//action
			}
			shiftStack = true;
		}
		else {shiftStack = false;}
	}
}
